version: "2"
linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - goprintffuncname
    - gosec
    - makezero
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testpackage
    - unconvert
    - wastedassign
  settings:
    lll:
      line-length: 180
      tab-width: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
