on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

name: tests
jobs:
  # Образец взял из https://github.com/mvdan/github-actions-golang
  tests:
    strategy:
      matrix:
        go-version:
          - "1.17.x"
        os:
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build tgp
        run: go build -v ./cmd/tgp
      - name: Run tests
        run: go test ./... -v -cover -coverpkg=./... -shuffle on

  # https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.42
          args: --verbose
